#!/bin/bash

(( $# > 0 )) || (echo "Usage: $0 <file_with_macro_names>" >&2 ; exit -1)

file_with_defines=$1

grep -F -f "$file_with_defines" -oh `find gdk/ -name "*.h" -or -name "*.c"` `find monetdb5/ -name "*.h" -or -name "*.c"` | sort | uniq
